### ISSUE TITLE
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed on node 9.2.1

### ISSUE THREAD

**Issue by johnykov** [doxout/recluster#48]
Hi, I see there is a problem on node 9.2.1 while sending kill -s SIGUSR2 51865

my server.js file is
```
const express = require('express')
const app = express()

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```
and cluster.js taken from your example

```
$ node cluster.js
spawned cluster, kill -s SIGUSR2 51865 to reload
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Got SIGUSR2, reloading cluster...
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
Example app listening on port 3000!
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:606:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at killTimeout (/Users/jankowalski/3prty/JS/my-recluster/node_modules/recluster/index.js:134:24)
    at EventEmitter.workerReplaceTimeoutTerminate (/Users/jankowalski/3prty/JS/my-recluster/node_modules/recluster/index.js:111:9)
    at EventEmitter.emit (events.js:159:13)
    at emit (/Users/jankowalski/3prty/JS/my-recluster/node_modules/recluster/index.js:53:19)
    at EventEmitter.workerDisconnect (/Users/jankowalski/3prty/JS/my-recluster/node_modules/recluster/index.js:148:36)
    at EventEmitter.emit (events.js:159:13)
    at ChildProcess.worker.process.once (internal/cluster/master.js:207:13)
    at Object.onceWrapper (events.js:254:19)
```

works fine on node 8.2.1

**Comment by JohnXLivingston** [comment]
Is recluster still maintained? I have the same issue with node v10.19.0. It seems @f8k8 has a fix, but the PR is not accepted yet.
